version: '3.8'

services:

  postgres:
    container_name: mcc-database
    image: postgis/postgis:13-master
    ports:
      - "5432:5432"
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  directus:
    container_name: mcc-backend
    restart: unless-stopped
    build:
      context: "./directus"
      dockerfile: "Dockerfile"
    ports:
      - "8055:8055"
    volumes:
      - ./directus/snapshots:/directus/snapshots
      - ./directus/extensions:/directus/extensions
      - ./directus/uploads:/directus/uploads
      - ./directus/database:/directus/database
    environment:
      PORT: '8055'
      KEY: ${KEY}
      SECRET: ${SECRET}
      CACHE_ENABLED: 'true'
      CACHE_AUTO_PURGE: 'true'
      CORS_ENABLED: 'true'
      CORS_ORIGIN: '*'
      DB_CLIENT: 'pg'
      DB_HOST: 'postgres'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'
      ADMIN_EMAIL: 'admin@example.com'
      PUBLIC_URL: 'http://localhost:3000'
      EMAIL_FROM: 'no-reply@mattclegg.dev'
      EMAIL_DOMAIN: 'mattclegg.dev'
      EMAIL_TRANSPORT: 'smtp'
      ADMIN_PASSWORD: 'password'
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
      PASSWORD_RESET_URL_ALLOW_LIST: 'http://localhost:3000/reset-password'
      IGNORE_MAIL: 'true'
      STRIPE_KEY: ${STRIPE_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}

  frontend:
    container_name: mcc-frontend
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
      target: base
    environment:
      NODE_ENV: 'development'
      BASE_URL: 'http://localhost:3000'
      NUXT_DIRECTUS_URL: 'http://host.docker.internal:8055'
      STRIPE_KEY: ${STRIPE_KEY}
      NUXT_DIRECTUS_STATIC_TOKEN: ${NUXT_DIRECTUS_STATIC_TOKEN}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "24678:24678"
      - "3000:3000"
    volumes:
      - ./frontend/src:/opt/node_app/app/src
      - ./frontend/.npmrc:/opt/node_app/app/.npmrc
      - ./frontend/nuxt.config.ts:/opt/node_app/app/nuxt.config.ts
      - ./frontend/tailwind.config.ts:/opt/node_app/app/tailwind.config.ts
      - ./frontend/tsconfig.json:/opt/node_app/app/tsconfig.json
      - ./frontend/package.json:/opt/node_app/app/package.json
      - ./frontend/package-lock.json:/opt/node_app/app/package-lock.json
    command: ["npm", "run", "dev"]
